url:              https://i.makelove.expert
baseurl:          /simonmysun.github.io

markdown:         kramdown
highlighter:      rouge
paginate:         4

title:            MY Sun
description:      "MY Sun's homepage"
